void drawScene(void);
void update(int);
void setup(void);
void resize(int, int);
void keyInput(unsigned char, int, int);
void specialKeyInput(int, int, int);
void mouse(int, int, int, int);
void move(int, int);
void tick(void);
void drawShape(void);
void drawCubes(void);
int nextStepAllowed(int, int, int);
void rotate(int);
void lockShape(void);
void removeRows(void);
int newShape(void);
void keyUp(void);
void writeString(void*, char*);
void drawHud(void);
void drawGame(void);
void restart(void);
void setColor(int);
